import type { ProColumns } from '@ant-design/pro-components';
import { formatCurrency } from '../utils/formatters';
import type { CampaignData, PlacementData } from '../types/adPlacementReportTypes';
// 广告位表格列配置
export const placementColumns: ProColumns<PlacementData>[] = [
  {
    title: '广告位',
    dataIndex: 'placement',
    width: 200,
    fixed: 'left',
    ellipsis: true,
    search: false,
  },
  {
    title: '展示量',
    dataIndex: 'impressions',
    align: 'right',
    sorter: (a, b) => a.impressions - b.impressions,
    valueType: 'digit',
    search: false,
  },
  {
    title: '点击量',
    dataIndex: 'clicks',
    align: 'right',
    sorter: (a, b) => a.clicks - b.clicks,
    valueType: 'digit',
    search: false,
  },
  {
    title: '花费',
    dataIndex: 'spend',
    align: 'right',
    sorter: (a, b) => a.spend - b.spend,
    render: (text: any) => formatCurrency(text),
    search: false,
  },
  {
    title: '销售额',
    dataIndex: 'sales',
    align: 'right',
    sorter: (a, b) => a.sales - b.sales,
    render: (text: any) => formatCurrency(text),
    search: false,
  },
  {
    title: '订单数',
    dataIndex: 'orders',
    align: 'right',
    sorter: (a, b) => a.orders - b.orders,
    valueType: 'digit',
    search: false,
  },
  {
    title: 'ACOS',
    dataIndex: 'acos',
    align: 'right',
    valueType: 'percent',
    sorter: (a, b) => a.acos - b.acos,
    search: false,
  },
  {
    title: 'ROAS',
    dataIndex: 'roas',
    align: 'right',
    valueType: 'digit',
    sorter: (a, b) => a.roas - b.roas,
    search: false,
  },
  {
    title: '点击率',
    dataIndex: 'ctr',
    align: 'right',
    valueType: 'percent',
    sorter: (a, b) => a.ctr - b.ctr,
    search: false,
  },
  {
    title: '转化率',
    dataIndex: 'conversionRate',
    align: 'right',
    valueType: 'percent',
    sorter: (a, b) => a.conversionRate - b.conversionRate,
    search: false,
  },
];

// 广告活动表格列配置
export const campaignColumns: ProColumns<CampaignData>[] = [
  {
    title: '广告活动',
    dataIndex: 'campaignName',
    fixed: 'left',
    width: 200,
    search: false,
    ellipsis: true,
    onCell: (record: CampaignData) => ({
      rowSpan: record.isFirstPlacement ? record.placementCount : 0
    }),
  },
  {
    title: '广告位',
    dataIndex: 'placement',
    width: 150,
    search: false,
    ellipsis: true,
  },
  {
    title: '展示量',
    dataIndex: 'impressions',
    valueType: 'digit',
    align: 'right',
    fieldProps: { precision: 0 },
    search: false,
  },
  {
    title: '点击量',
    dataIndex: 'clicks',
    valueType: 'digit',
    align: 'right',
    fieldProps: { precision: 0 },
    search: false,
  },
  {
    title: '花费',
    dataIndex: 'spend',
    align: 'right',
    render: (text: any) => formatCurrency(text),
    fieldProps: { precision: 2 },
    search: false,
  },
  {
    title: '销售额',
    dataIndex: 'sales',
    align: 'right',
    render: (text: any) => formatCurrency(text),
    fieldProps: { precision: 2 },
    search: false,
  },
  {
    title: 'ACOS',
    dataIndex: 'acos',
    valueType: 'percent',
    align: 'right',
    fieldProps: { precision: 2 },
    search: false,
  },
  {
    title: 'ROAS',
    dataIndex: 'roas',
    valueType: 'digit',
    align: 'right',
    fieldProps: { precision: 2 },
    search: false,
  },
  {
    title: '点击率',
    dataIndex: 'ctr',
    valueType: 'percent',
    align: 'right',
    fieldProps: { precision: 2 },
    search: false,
  },
  {
    title: '转化率',
    dataIndex: 'conversionRate',
    valueType: 'percent',
    align: 'right',
    fieldProps: { precision: 2 },
    search: false,
  },
  {
    title: 'CPC',
    dataIndex: 'cpc',
    align: 'right',
    render: (text: any) => formatCurrency(text),
    fieldProps: { precision: 2 },
    search: false,
  },
];

// 子表格列定义
export const subCampaignColumns: ProColumns<CampaignData>[] = [
  {
    title: '广告活动',
    dataIndex: 'campaignName',
    ellipsis: true,
  },
  {
    title: '展示量',
    dataIndex: 'impressions',
    valueType: 'digit',
    sorter: (a, b) => a.impressions - b.impressions,
    align: 'right',
  },
  {
    title: '点击量',
    dataIndex: 'clicks',
    valueType: 'digit',
    sorter: (a, b) => a.clicks - b.clicks,
    align: 'right',
  },
  {
    title: '花费',
    dataIndex: 'spend',
    align: 'right',
    sorter: (a, b) => a.spend - b.spend,
    render: (text: any) => formatCurrency(text),
  },
  {
    title: '销售额',
    dataIndex: 'sales',
    align: 'right',
    sorter: (a, b) => a.sales - b.sales,
    render: (text: any) => formatCurrency(text),
  },
  {
    title: 'ACOS',
    dataIndex: 'acos',
    valueType: 'percent',
    sorter: (a, b) => a.acos - b.acos,
    align: 'right',
  },
  {
    title: 'ROAS',
    dataIndex: 'roas',
    valueType: 'digit',
    sorter: (a, b) => a.roas - b.roas,
    align: 'right',
  },
  {
    title: '点击率',
    dataIndex: 'ctr',
    valueType: 'percent',
    sorter: (a, b) => a.ctr - b.ctr,
    align: 'right',
  },
  {
    title: '转化率',
    dataIndex: 'conversionRate',
    valueType: 'percent',
    sorter: (a, b) => a.conversionRate - b.conversionRate,
    align: 'right',
  },
  {
    title: 'CPC',
    dataIndex: 'cpc',
    align: 'right',
    sorter: (a, b) => a.cpc - b.cpc,
    render: (text: any) => formatCurrency(text),
  },
];


 // 定义子表格的列，与campaignColumns类似但去掉广告位列
 export const subColumns: ProColumns<CampaignData>[] = [
  {
    title: '广告活动',
    dataIndex: 'campaignName',
  
    ellipsis: true,
  },
  {
    title: '展示量',
    dataIndex: 'impressions',
    valueType: 'digit',
    sorter: (a, b) => a.impressions - b.impressions,
    align: 'right',
  },
  {
    title: '点击量',
    dataIndex: 'clicks',
    valueType: 'digit',
    sorter: (a, b) => a.clicks - b.clicks,
    align: 'right',
  },
  {
    title: '花费',
    dataIndex: 'spend',
    align: 'right',
    sorter: (a, b) => a.spend - b.spend,
    render: (text: any) => formatCurrency(text),
  },
  {
    title: '销售额',
    dataIndex: 'sales',
    align: 'right',
    sorter: (a, b) => a.sales - b.sales,
    render: (text: any) => formatCurrency(text),
  },
  {
    title: 'ACOS',
    dataIndex: 'acos',
    valueType: 'percent',
    sorter: (a, b) => a.acos - b.acos,
    align: 'right',
  },
  {
    title: 'ROAS',
    dataIndex: 'roas',
    valueType: 'digit',
    sorter: (a, b) => a.roas - b.roas,
    align: 'right',
  },
  {
    title: '点击率',
    dataIndex: 'ctr',
    valueType: 'percent',
    sorter: (a, b) => a.ctr - b.ctr,
    align: 'right',
  },
  {
    title: '转化率',
    dataIndex: 'conversionRate',
    valueType: 'percent',
    sorter: (a, b) => a.conversionRate - b.conversionRate,
    align: 'right',
  },
  {
    title: 'CPC',
    dataIndex: 'cpc',
    align: 'right',
    sorter: (a, b) => a.cpc - b.cpc,
    render: (text: any) => formatCurrency(text),
  },
];